name: Build

on:
    push:
        branches: ['**']
    pull_request:
        branches: ['master']

jobs:
    verify:
        runs-on: ubuntu-latest
        timeout-minutes: 10
        strategy:
            matrix:
                node-version: [22.x]
        steps:
            - uses: actions/checkout@v4
            - name: Use Node.js ${{ matrix.node-version }}
              uses: actions/setup-node@v4
              with:
                  node-version: ${{ matrix.node-version }}
                  cache: 'npm'
            - name: Install dependencies
              run: npm ci
            - name: Cleanup working directory
              run: npm run ci_clean
            - name: Run ESLint
              run: npm run ci_lint
            - name: Run prettier verification
              run: npm run ci_check_format
    build:
        runs-on: ubuntu-latest
        timeout-minutes: 10
        strategy:
            matrix:
                node-version: [22.x]
        steps:
            - uses: actions/checkout@v4
            - name: Use Node.js ${{ matrix.node-version }}
              uses: actions/setup-node@v4
              with:
                  node-version: ${{ matrix.node-version }}
                  cache: 'npm'
            - name: Install dependencies
              run: npm ci
            - name: Cleanup working directory
              run: npm run ci_clean
            - name: Run Build
              run: npm run ci_build
    test:
        runs-on: ubuntu-latest
        timeout-minutes: 10
        strategy:
            matrix:
                node-version: [22.x]
        steps:
            - uses: actions/checkout@v4
            - name: Use Node.js ${{ matrix.node-version }}
              uses: actions/setup-node@v4
              with:
                  node-version: ${{ matrix.node-version }}
                  cache: 'npm'
            - name: Install dependencies
              run: npm ci
            - name: Cleanup working directory
              run: npm run ci_clean
            - name: Run Tests
              run: npm run ci_test
