name: Publish Package to npmjs
on:
    release:
        types: [published]
jobs:
    build:
        runs-on: ubuntu-latest
        strategy:
            matrix:
                node-version: [22.x]
        permissions:
            contents: read
            id-token: write
        steps:
            - uses: actions/checkout@v4
            # Setup .npmrc file to publish to npm
            - uses: actions/setup-node@v4
              with:
                  node-version: ${{ matrix.node-version }}
                  registry-url: 'https://registry.npmjs.org'
            - name: Install dependencies
              run: npm ci
            - name: Cleanup working directory
              run: npm run ci_clean
            - name: Create package
              run: npm run package
            - run: npm publish --provenance --access public
              env:
                  NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
